[tools]
go = "latest"
node = "latest"
uv = "latest"
cargo-binstall = "latest"
usage = "latest"
python = "3.13.2"
teleport-ent = "latest"

[tasks.rustme]
run = 'cargo binstall mise du-dust eza bat zoxide bottom ripgrep fd-find cargo-udeps fd-find ouch rewrk hx git-delta stylua tidy-viewer nu'

[settings]
idiomatic_version_file_enable_tools = ["terraform"]

[settings.pipx]
uvx = true
