theme = "slick"
[icons]
icons = "material"
[icons.overrides]
bat = "  "
bat_full = "  "
bat_charging = "  "
bat_discharging = "  "
volume_muted = "ﱝ"
music_play = ""
music_pause = "懶"
music_next = "怜"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 20
format = " {min}°/{max}°  {average}°"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
format = "{percentage}% {time} {power}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
