require('gersondev.functions')
require('gersondev.opt')
require('gersondev.plugins')

require('gersondev.lualine-config')
require('gersondev.nvim-tree')
require('gersondev.nvim-lsp')
require('gersondev.cmp')
require('gersondev.dap')
require('gersondev.nvim-metals')
require('gersondev.null-ls')
require('gersondev.trouble')
require('gersondev.nvim-telescope')
require('gersondev.nvim-treesitter')
require('gersondev.neogit')
require('gersondev.gitsigns')
require "gitlinker".setup()
require('gersondev.theme')
require('Comment').setup()
require('impatient')
